# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rohit Kulkarni
email: rkulkar1@stevens.edu rohit666kulkarni@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Software Engineer from Stevens Institute of Technology, Hoboken, NJ.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rohit-kulkarni.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  rohitk10

# Build settings
markdown: kramdown

#theme: jekyll-theme-cayman
